### ISSUE TITLE
TextTransformer [NSView stringValue]: unrecognized selector sent to instance

### ISSUE THREAD

**Issue by team-hq** [twostraws/SwiftOnSundays#5]
I love following your YT videos, Paul. Thanks for those.

I'm running into this issue with Text Transformer and for the life of me I can't figure out where this error is coming from.  I've copied your code and ran it. The project runs and I can see the letter a inside task bar. However, when I click on it nothing happens and I get the following error thrown. I'm running 10.15.3 and 11.4 Xcode. If you can shed some light on the issue it would be greatly appreciated.

2020-04-14 23:53:50.069756+1000 TextTransformer[11998:441480] -[NSView stringValue]: unrecognized selector sent to instance 0x1005021f0
2020-04-14 23:53:50.069960+1000 TextTransformer[11998:441480] [General] -[NSView stringValue]: unrecognized selector sent to instance 0x1005021f0
2020-04-14 23:53:50.072030+1000 TextTransformer[11998:441480] [General] (
	0   CoreFoundation                      0x00007fff3872b8ab __exceptionPreprocess + 250
	1   libobjc.A.dylib                     0x00007fff6e9e5805 objc_exception_throw + 48
	2   CoreFoundation                      0x00007fff387aab61 -[NSObject(NSObject) __retain_OA] + 0
	3   CoreFoundation                      0x00007fff3868fadf ___forwarding___ + 1427
	4   CoreFoundation                      0x00007fff3868f4b8 _CF_forwarding_prep_0 + 120
	5   TextTransformer                     0x00000001000058ad $s15TextTransformer14ViewControllerC11typeChangedyyypF + 1261
	6   TextTransformer                     0x0000000100004a76 $s15TextTransformer14ViewControllerC11viewDidLoadyyF + 182
	7   TextTransformer                     0x0000000100004b5b $s15TextTransformer14ViewControllerC11viewDidLoadyyFTo + 43
	8   AppKit                              0x00007fff358f017d -[NSViewController _sendViewDidLoad] + 87
	9   AppKit                              0x00007fff3594ad0e _noteLoadCompletionForObject + 643
	10  AppKit                              0x00007fff358514ad -[NSIBObjectData nibInstantiateWithOwner:options:topLevelObjects:] + 1930
	11  AppKit                              0x00007fff358d793a -[NSNib _instantiateNibWithExternalNameTable:options:] + 647
	12  AppKit                              0x00007fff358d75be -[NSNib _instantiateWithOwner:options:topLevelObjects:] + 143
	13  AppKit                              0x00007fff358d692f -[NSViewController loadView] + 345
	14  AppKit                              0x00007fff358d6676 -[NSViewController _loadViewIfRequired] + 72
	15  AppKit                              0x00007fff358d65f3 -[NSViewController view] + 23
	16  AppKit                              0x00007fff35bdf799 -[NSPopover showRelativeToRect:ofView:preferredEdge:] + 264
	17  TextTransformer                     0x000000010000a15f $s15TextTransformer11AppDelegateC12showSettingsyyF + 1087
	18  TextTransformer                     0x000000010000a47b $s15TextTransformer11AppDelegateC12showSettingsyyFTo + 43
	19  AppKit                              0x00007fff35ab7d38 -[NSApplication(NSResponder) sendAction:to:from:] + 299
	20  AppKit                              0x00007fff35ab7bd4 -[NSControl sendAction:to:] + 86
	21  AppKit                              0x00007fff35ab3bed NSControlTrackMouse + 1745
	22  AppKit                              0x00007fff35ab34f4 -[NSCell trackMouse:inRect:ofView:untilMouseUp:] + 130
	23  AppKit                              0x00007fff35ab33b4 -[NSButtonCell trackMouse:inRect:ofView:untilMouseUp:] + 691
	24  AppKit                              0x00007fff35fedc1d -[NSStatusBarButtonCell trackMouse:inRect:ofView:untilMouseUp:] + 305
	25  AppKit                              0x00007fff35ab2733 -[NSControl mouseDown:] + 748
	26  AppKit                              0x00007fff35ab0b0d -[NSWindow(NSEventRouting) _handleMouseDownEvent:isDelayedEvent:] + 4907
	27  AppKit                              0x00007fff35a1ac5c -[NSWindow(NSEventRouting) _reallySendEvent:isDelayedEvent:] + 2612
	28  AppKit                              0x00007fff35a1a005 -[NSWindow(NSEventRouting) sendEvent:] + 349
	29  AppKit                              0x00007fff35fef541 -[NSStatusBarWindow sendEvent:] + 347
	30  AppKit                              0x00007fff35a1837c -[NSApplication(NSEvent) sendEvent:] + 352
	31  AppKit                              0x00007fff358640cf -[NSApplication run] + 707
	32  AppKit                              0x00007fff35836465 NSApplicationMain + 777
	33  TextTransformer                     0x000000010000a6ed main + 13
	34  libdyld.dylib                       0x00007fff6fd537fd start + 1
	35  ???                                 0x0000000000000003 0x0 + 3
)

**Comment by twostraws** [comment]
If you're looking for help, please use the [Hacking with Swift Forums](https://www.hackingwithswift.com/forums).
